---

- name: "configuration play." 
  environment:
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_PORT: 5432
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - ansible_host_key_checking: false   # to skip the user confirmation on SSH authentication

  pre_tasks:
  - name: "wait 600 seconds for target connection to become reachable/usable."
    shell: sleep 6
  - name: "install python for Ansible."
    shell: sudo apt-get update && sudo apt-get install python3
      # Your code here
  roles:
  - configure-server