
---

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
- name: Creates directory
  file:
    path: ~/deploy
    state: directory

- name: uncompress the copied backend folder
  unarchive:
    src: "/root/project/test.tar.gz"   #../../../../backend /.dist , /dist ,  #in build , prev value was npm run build
    dest: "~/deploy"

- name: Build
  become: true
  shell: |
    cd /home/ubuntu/deploy/backend
    npm install
    npm run build   #

- name: Executing node
  shell: |
    cd /home/ubuntu/deploy/backend
    pm2 start npm --name backend -- start
    


