
---
- name: Creates directory
  file:
    path: ~/deploy
    state: directory

- name: Copy index test page
  template:
    src: "/root/project/backend/test2.txt"   #../../../../backend
    dest: "~/deploy"

