
---
- name: Creates directory
  file:
    path: ~/deploy
    state: directory

- name: Copy index test page
  template:
    src: "/root/project/backend/./dist"   #../../../../backend /.dist , /dist , 
    dest: "~/deploy"

