
---
- name: Creates directory
  file:
    path: ~/deploy
    state: directory

- name: Copy index test page
  template:
    src: "../../../../backend/./dist"   #../../../../backend
    dest: "~/deploy"

